In [6]:
import cv2
import numpy as np

In [12]:
img = cv2.imread('3.jpeg',0)

In [13]:
print(img)

[[47 46 45 ... 47 45 45]
 [45 46 47 ... 46 46 47]
 [46 47 49 ... 45 47 47]
 ...
 [43 46 42 ... 40 40 39]
 [43 43 45 ... 40 40 40]
 [41 42 44 ... 40 40 40]]


In [14]:
# def cv_imread(file_path):
#     cv_img = cv2.imdecode(np.fromfile(file_path, dtype=np.uint8), -1)
#     return cv_img
# file_path = '3.jpeg'
# img = cv_imread(file_path)
# print(img)

In [15]:
dilated_img = cv2.dilate(img, np.ones((7,7), np.uint8))

In [16]:
bg_img = cv2.medianBlur(dilated_img, 21)

In [17]:
diff_img = 255 - cv2.absdiff(img, bg_img)

In [18]:
norm_img = diff_img.copy()

In [19]:
cv2.normalize(diff_img, norm_img, alpha=0, beta=255, norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_8UC1)

array([[252, 251, 250, ..., 252, 250, 250],
       [250, 251, 252, ..., 251, 251, 252],
       [251, 252, 255, ..., 250, 252, 252],
       ...,
       [251, 254, 249, ..., 252, 252, 251],
       [251, 251, 254, ..., 252, 252, 254],
       [249, 250, 252, ..., 252, 254, 254]], dtype=uint8)

In [20]:
_, thr_img = cv2.threshold(norm_img, 230, 0, cv2.THRESH_TRUNC)

In [21]:
cv2.normalize(thr_img, thr_img, alpha=0, beta=255, norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_8UC1)

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)